import necessary libraries

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

loading the dataset and all the other description

In [12]:
import pandas as pd
import kagglehub

# Download the dataset locally using Kaggle Hub
dataset_path = kagglehub.dataset_download("sazidthe1/sustainable-development-report")

# Now read the specific CSV file using pandas
file_path = f"{dataset_path}/sustainable_development_report_2023.csv"
df = pd.read_csv(file_path)

df.head()  # Preview the first few rows

,country_code,country,region,overall_score,goal_1_score,goal_2_score,goal_3_score,goal_4_score,goal_5_score,goal_6_score,...,goal_8_score,goal_9_score,goal_10_score,goal_11_score,goal_12_score,goal_13_score,goal_14_score,goal_15_score,goal_16_score,goal_17_score
0,FIN,Finland,OECD,86.760595,99.5750,60.886750,95.386385,97.169333,92.11125,94.3276,...,86.789000,95.995714,98.4685,91.233750,60.059571,68.793667,87.928000,85.0700,92.521091,75.60100
1,SWE,Sweden,OECD,85.981397,98.8885,63.074125,96.904000,99.761667,91.44025,95.0576,...,84.966429,97.586286,94.9650,90.389250,56.830571,70.031000,69.348667,80.1882,88.508455,85.77025
2,DNK,Denmark,OECD,85.683637,99.2155,71.025250,95.398500,99.339667,86.99800,90.7316,...,87.562429,96.984857,98.1560,93.038500,44.571714,60.780667,76.303333,92.7924,93.844909,82.14800
3,DEU,Germany,OECD,83.358447,99.5105,72.366000,93.039357,97.162667,81.92025,88.4434,...,86.967286,95.788429,88.1470,90.096500,55.412857,64.002000,73.996000,79.2318,89.457545,84.39025
4,AUT,Austria,OECD,82.280189,99.4510,73.067500,92.468000,97.914333,84.57925,92.1636,...,83.274143,96.982143,94.6345,92.473667,49.623286,57.332000,NaN,73.5836,87.911455,71.13025

Explore the dataset using:*
		.info()
		.describe()
		.isnull().sum()

In [13]:
import pandas as pd
import kagglehub

# Download the dataset locally using Kaggle Hub
dataset_path = kagglehub.dataset_download("sazidthe1/sustainable-development-report")

# Now read the specific CSV file using pandas
file_path = f"{dataset_path}/sustainable_development_report_2023.csv"
df = pd.read_csv(file_path)

# 1. Get general information about the dataset
print("=== Data Info ===")
print(df.info())

# 2. Get summary statistics for numerical columns
print("\n=== Data Description ===")
print(df.describe())

# 3. Check for missing values in each column
print("\n=== Missing Values ===")
print(df.isnull().sum())

=== Data Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country_code   166 non-null    object
 1   country        166 non-null    object
 2   region         166 non-null    object
 3   overall_score  166 non-null    float64
 4   goal_1_score   151 non-null    float64
 5   goal_2_score   166 non-null    float64
 6   goal_3_score   166 non-null    float64
 7   goal_4_score   166 non-null    float64
 8   goal_5_score   166 non-null    float64
 9   goal_6_score   166 non-null    float64
 10  goal_7_score   166 non-null    float64
 11  goal_8_score   166 non-null    float64
 12  goal_9_score   166 non-null    float64
 13  goal_10_score  149 non-null    float64
 14  goal_11_score  166 non-null    float64
 15  goal_12_score  166 non-null    float64
 16  goal_13_score  166 non-null    float64
 17  goal_14_score  126 non-null    float64
 18  goal_15_score  166 non-null    float64
 19  goal_16_score  166 non-null    float64
 20  goal_17_score  166 non-null    float64
dtypes: float64(18), object(3)
memory usage: 27.4+ KB
None

=== Data Description ===
       overall_score  goal_1_score  goal_2_score  goal_3_score  goal_4_score  \
count     166.000000    151.000000    166.000000    166.000000    166.000000
mean       67.549197     75.234401     59.799100     69.694078     76.512968
std        10.295499     31.169948     10.620853     20.354575     23.181919
min        38.676086      0.000000     19.805800     12.952714      1.232250
25%        60.547488     55.779250     54.007188     51.860089     61.417938
50%        69.376528     93.300500     61.027500     75.437629     84.772875
75%        74.947511     98.950750     67.264335     85.524428     95.644063
max        86.760595    100.000000     83.401125     97.115143     99.761667

       goal_5_score  goal_6_score  goal_7_score  goal_8_score  goal_9_score  \
count    166.000000    166.000000    166.000000    166.000000    166.000000
mean      63.285420     66.710744     61.413598     71.952935     51.600648
std       16.399691     14.091641     20.364351     10.592308     26.561680
min       13.054750     32.600000      8.697000     39.535000      1.654833
25%       51.046250     55.237250     47.521312     66.426857     30.206464
50%       65.869875     67.878000     68.612750     73.157643     48.168798
75%       76.137000     76.044200     74.364000     79.626036     74.713036
max       94.021667     95.057600     99.550750     93.382750     99.128857

       goal_10_score  goal_11_score  goal_12_score  goal_13_score  \
count     149.000000     166.000000     166.000000     166.000000
mean       62.917889      72.181106      79.775904      82.119387
std        27.348955      18.215526      16.092924      21.175602
min         0.000000      13.826250      37.729429       0.000000
25%        41.608000      59.969813      68.592464      72.543000
50%        69.700500      76.851500      84.566024      90.903000
75%        84.612500      86.499437      94.084750      96.710875
max       100.000000      99.858000      98.811200      99.925333

       goal_14_score  goal_15_score  goal_16_score  goal_17_score
count     126.000000     166.000000     166.000000     166.000000
mean       65.494968      66.637486      61.546404      60.954819
std        11.475977      14.175602      15.517449      12.991856
min        36.579400      26.477500      29.438000      29.350000
25%        57.647625      56.606900      49.029477      50.854917
50%        65.412250      66.295700      60.908687      60.805000
75%        72.992375      76.585000      73.716061      71.647188
max        90.394750      97.849000      93.844909      94.026500

=== Missing Values ===
country_code      0
country           0
region            0
overall_score     0
goal_1_score     15
goal_2_score      0
goal_3_score      0
goal_4_score      0
goal_5_score      0
goal_6_score      0
goal_7_score      0
goal_8_score      0
goal_9_score      0
goal_10_score    17
goal_11_score     0
goal_12_score     0
goal_13_score     0
goal_14_score    40
goal_15_score     0
goal_16_score     0
goal_17_score     0
dtype: int64